// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public partial class GamePlayService{

	/// <summary>
	/// The visited boolean. check block is visited or bot
	/// </summary>
	private bool[,] visited ;
	
	/// <summary>
	/// The best_way , use 2 hint 
	/// </summary>
	private List<Block> best_way;
	
	/// <summary>
	/// The number of block
	/// </summary>
	private Vector2 blockNum ;
	
	/// <summary>
	/// The array of blocks
	/// </summary>
	private Block[,] block;
	
	/// <summary>
	/// Inits the block data
	/// </summary>
	/// <param name="blockNum">number of block</param>
	public void initBlock(Vector2 blockNum,Block[,] block)
	{
		this.blockNum = blockNum;
		this.block = block;
		visited = new bool[(int)blockNum.x, (int)blockNum.y];
		best_way = new List<Block>();
	}
	
	/// <summary>
	/// Checks the is same type of block.
	/// </summary>
	/// <returns><c>true</c>, if is same type of block was checked, <c>false</c> otherwise.</returns>
	/// <param name="b1">B1.</param>
	/// <param name="b2">B2.</param>
	private bool checkIsSameTypeOfBlock(Block b1,Block b2)
	{
		return (b1._type == b2._type);
	}
	
	/// <summary>
	/// Search the specified way for block[x, y], result will be kept in matchingSet.
	/// </summary>
	/// <param name="x">The x coordinate.</param>
	/// <param name="y">The y coordinate.</param>
	/// <param name="type">Type of block</param>
	/// <param name="matchingSet">Matching set.</param>
	private void Search(int x,int y,Block type,List<Block> matchingSet)
	{
		
		if(checkIsSameTypeOfBlock(block[x, y], type)) {
			matchingSet.Add(block[x, y]);
			visited[x, y] = true;
			if(x < blockNum.x - 1 && !visited[x + 1, y]) {
				Search(x + 1, y, type, matchingSet);
			}
			
			if(y < blockNum.y - 1 && !visited[x, y + 1]) {
				Search(x, y + 1, type, matchingSet);
			}
			
			if(x > 0 && !visited[x - 1, y]) {
				Search(x - 1, y, type, matchingSet);
			}
			
			if(y > 0 && !visited[x, y - 1]) {
				Search(x, y - 1, type, matchingSet);
			}
			
			if(x % 2 != 0) {
				if(x < blockNum.x - 1 && y > 0 && !visited[x + 1, y - 1]) {
					Search(x + 1, y - 1, type, matchingSet);
				}
				
				if(x > 0 && y > 0 && !visited[x - 1, y - 1]) {
					Search(x - 1, y - 1, type, matchingSet);
				}
			} else {
				if(x < blockNum.x - 1 && y < blockNum.y - 1 && !visited[x + 1, y + 1]) {
					Search(x + 1, y + 1, type, matchingSet);
				}
				
				if(x > 0 && y < blockNum.y - 1 && !visited[x - 1, y + 1]) {
					Search(x - 1, y + 1, type, matchingSet);
				}
			}
		}
	}
	
	/// <summary>
	/// Clears the visited match.
	/// </summary>
	private void ClearVisitedMatch()
	{
		for(int x = 0;x < (int) blockNum.x;x ++) {
			for(int y = 0;y < (int) blockNum.y;y++) {
				visited[x, y] = false;
			}
		}
	}
	
	/// <summary>
	/// Finds all the matches.
	/// </summary>
	private void FindMatches()
	{
		ClearVisitedMatch();
		best_way.Clear();
		
		for(int x = 0;x < (int) blockNum.x;x++) {
			for(int y = 0;y <  (int) blockNum.y;y++) {
				if(!visited[x, y]) {
					visited[x, y] = true;
					List<Block> matchingSet = new List<Block>();
					Search(x, y, block[x, y], matchingSet);
					if(matchingSet.Count > best_way.Count && matchingSet.Count > 2) {
						best_way = matchingSet;
					}
				}
			}
		}
		
	}
	
	/// <summary>
	/// Finds the hint that has maximum same type of blocks
	/// </summary>
	public List<Block> FindHint()
	{
		FindMatches();
		return best_way;
	}

}
