// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public partial class GamePlayService{
	///start caculate exp
	/// <summary>
	/// Caculates the exp.
	
	/// Cách tính belly.
	///	1. Ăn 3 block k được tính 
	///	2. Ăn 4 block: 1
	///	3. Ắn 5 block: 2
	///	4. Ăn 6 block: 4
	///	belly = 2^(num_block - 4)
	/// </summary>
	/// <returns>The exp.</returns>
	/// <param name="numBlocks">Number blocks.</param>
	public int calculateExp(int numBlocks)
	{
		if(numBlocks < 4) {
			return 0;
		}
		return 2 << (numBlocks - 4);
	}
	
	
	/// <summary>
	/// Cách tính score.
	//    Score 
	//        1. Có phụ thuộc vào level nhưng mà ít. Level up -> score up
	//            2. Skill: up -> up
	//            3. Combo up -> up
	//            4. Item up -> up
	//            5. Fever time
	//            Score 1 lần ăn
	//            
	//            score = a * 2^(block -3) + (combo + b)
	//            trong đó
	//            Block: số block ăn được trong 1 lần vuốt
	//            combo: số lượng combo hiện tại
	//            a: const = 20
	//            b: const = 50
	/// </summary>
	/// <returns>The score.</returns>
	/// <param name="numBlocks">Number blocks.</param>
	/// <param name="combo">Combo.</param>
	public int calculateScore(int numBlocks,int combo,int a = 20,int b = 50)
	{
		if(numBlocks < 3)
			return (combo + b);
		return (a * (2 << (numBlocks - 3)) + (combo + b));
	}
	
	/// <summary>
	/// Cách tính belly.
	//    1. Ăn 3 block k được tính 
	//        2. Ăn 4 block: 1
	//            3. Ắn 5 block: 2
	//            4. Ăn 6 block: 4
	//            
	//            belly = 2^(num_block - 4)
	/// </summary>
	/// <returns>The belly.</returns>
	/// <param name="numBlocks">Number blocks.</param>
	public int calculateBelly(int numBlocks)
	{
		if(numBlocks < 4) {
			return 0;
		}
		return 2 << (numBlocks - 4);
	}

}
