// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;

namespace OPUnitTest
{
    [TestFixture()]
    public class UserServiceTest
    {
        [Test()]
        public void TestUpdateExp()
        {
            OPUser user = OPUserDAO.Instance.getCurrentUser();
            UserService.Instance.increaseExp(user, 10);
            Assert.AreEqual(user.Exp, 10);
        }
    }
}