// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
		

public class MonsterController : CharacterController
{
	[HideInInspector]
	public bool isRestored {get; set;}

	protected override void initMonsterAttributes ()
	{
		if(!isRestored)
			base.initMonsterAttributes ();
		else
		{
			this.initialHP = PlayerPrefs.GetFloat(Config.CURRENT_MONSTER_INITIAL_HP_KEY);
			this.currentHP = PlayerPrefs.GetFloat(Config.CURRENT_MONSTER_CURRENT_HP_KEY);
			this.UIMonsterHp.fillAmount = this.currentHP / this.initialHP;
		}
	}	
}

