// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using NUnit.Framework;
using System.Collections.Generic;
using System;


namespace UnityTest{

    [TestFixture()]
    public class OPUserDaoTest
    {
        [Test()]
        public void TestSelect ()
        {
            string dbpath  = Application.streamingAssetsPath + "/master.db";
            var db = new SQLiteDB();
            db.Open(dbpath);
			Debug.Log("I am ok");
            GenericDao<OPUser>.Instance.Drop(db);
            GenericDao<OPUser>.Instance.Create(db);
            
			OPUser hoge = new OPUser();
            hoge.User_id = 1;

            GenericDao<OPUser>.Instance.Put(db, hoge);

        }
    }
}

