// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using NUnit.Framework;
using System.Collections.Generic;
using System;


namespace UnityTest{

    [TestFixture()]
    public class OPUserDaoTest
    {
        [Test()]
        public void TestSelect ()
        {
            string dbpath  = Application.streamingAssetsPath + "/test_user.db";
            var db = new SQLiteDB();
            db.Open(dbpath);
            GenericDao<OPUser>.Instance.Drop(db);
            GenericDao<OPUser>.Instance.Create(db);
            
			OPUser hoge = new OPUser();
            hoge.Id = 1;
			hoge.Exp = 100;
			hoge.Health = 5;

            GenericDao<OPUser>.Instance.Put(db, hoge);

			List<OPUser> result = GenericDao<OPUser>.Instance.Get(db, "select * from OPUser where id = 1");

			Assert.AreEqual(1, result[0].Id);
			Assert.AreEqual(100, result[0].Exp);
			Assert.AreEqual(5, result[0].Health);
		}
    }
}

